"""Local chat agent: Laya screens and routes every message, an Ollama model writes the reply.

Per message, one Laya forward pass (about 20-60 ms) decides: attack (refuse), intent, and difficulty.
Easy messages go to TEXT_MODEL (small), hard ones to TEXT_MODEL_LARGE if set, else the same model.
"""

import os

import httpx

from .usecases import chat_route

HARD = 1.5  # difficulty score (0-3) at or above which the large model is used


def reply(history, model):
    base = os.environ.get("TEXT_MODEL_BASE_URL", "http://localhost:11434/v1").rstrip("/")
    key = os.environ.get("TEXT_MODEL_API_KEY")
    headers = {"Authorization": f"Bearer {key}"} if key else {}
    response = httpx.post(f"{base}/chat/completions", headers=headers, timeout=180,
                          json={"model": model, "messages": history})
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def system_prompt(model):
    return (
        f"You are a concise, helpful assistant. You are the model '{model}', running locally on this machine "
        "through a local model server (Ollama by default), not through any cloud API. Some open-weight models "
        "were trained on text generated by Claude or GPT-4 and mistakenly claim to be one of them; you must not "
        f"do that. If asked what model you are, say you are '{model}', running locally, not Claude, not GPT, "
        "and not from Anthropic or OpenAI."
    )


def turn(engine, history, message):
    """Returns (answer, route). Mutates history."""
    route = chat_route(engine, message)
    if route["attack"]:
        return "That looks like an attempt to override my instructions, so I did not send it to the model.", route
    small = os.environ.get("TEXT_MODEL", "qwen2.5:latest")
    model = os.environ.get("TEXT_MODEL_LARGE", small) if route["difficulty"] >= HARD else small
    if history and history[0].get("role") == "system":
        history[0]["content"] = system_prompt(model)  # keep it truthful even if TEXT_MODEL changed mid-session
    history.append({"role": "user", "content": message})
    answer = reply(history, model)
    history.append({"role": "assistant", "content": answer})
    route["model"] = model
    return answer, route


def repl(engine, once=None):
    engine.load()
    history = [{"role": "system", "content": system_prompt(os.environ.get("TEXT_MODEL", "qwen2.5:latest"))}]
    while True:
        try:
            message = once or input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            return
        if message:
            answer, route = turn(engine, history, message)
            print(f"[{route}]\n{answer}\n")
        if once:
            return
